name: xk6bundler
on:
  push:
    tags:
      - "v*"
jobs:
  xk6bundler:
    name: Bundle xk6 extensions
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        id: build
        uses: szkiba/xk6bundler@v0
        with:
          with: |
            github.com/szkiba/xk6-dashboard@v0.1.1
            github.com/szkiba/xk6-prometheus@v0.1.4
            github.com/szkiba/xk6-cache@v0.1.1
            github.com/szkiba/xk6-dotenv@v0.1.1
            github.com/szkiba/xk6-mock@v0.1.2
            github.com/szkiba/xk6-faker@v0.1.1
            github.com/szkiba/xk6-crypto@v0.1.3
            github.com/szkiba/xk6-jose@v0.1.2
            github.com/szkiba/xk6-yaml@v0.1.2
            github.com/szkiba/xk6-toml@v0.1.2
            github.com/szkiba/xk6-csv@v0.1.2
            github.com/szkiba/xk6-ansible-vault@v0.1.2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.build.outputs.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./${{ steps.build.outputs.dockerdir }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
